name: Automatically build on PR
on: [pull_request, workflow_dispatch]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Release Configuration
      run: |
        sed -i -r "s/(?<=project\.version \= ')([\d\.]+)(?:-\w+)?(?=')/\1-SNAPSHOT/" build.gradle
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - uses: "dciborow/action-github-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Experimental SNAPSHOT"
        generate_release_notes: This might contain uncertain features and bugs. Please be extra careful to local game files when using this.
        files: |
          LICENSE
          build/libs/**.jar
