name: Automatically build on PR
on: [pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - run: |
        echo 'key=$(curl --form file=@$(find / -name "build/libs/**.jar" | grep -v "source") https://file.io/ | jq ".key")' >> $GITHUB_OUTPUT
      id: get_file
    - name: Commit Comment
      uses: peter-evans/commit-comment@v2.0.1
      with:
        sha: ${{ github.event.pull_request.head.sha }}
        body: ${{ steps.get_file.outputs.key }}
        
